version: '3'

services:
  db_boilerplate:
    image: 'postgres:14.2-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - ./database/boilerplate:/var/lib/postgresql/data/

  be_boilerplate:
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    env_file:
      - .env
    environment:
      - PG_HOST=db_boilerplate
    depends_on:
      - db_boilerplate
    links:
      - db_boilerplate

  be_boilerplate_test:
    container_name: 'be_boilerplate_test'
    command: sh -c "echo 'Test container ready' && tail -f /dev/null"
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db_boilerplate
    links:
      - db_boilerplate
    env_file:
      - .env
    environment:
      - PG_HOST=db_boilerplate
    volumes:
      - .:/app/
      - /app/node_modules
