version: '3.8'

services:
  be_boilerplate:
    container_name: 'be_boilerplate'
    build: .
    restart: always
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - db_boilerplate
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - WAIT_HOSTS=db_boilerplate:5432

  db_boilerplate:
    container_name: 'db_boilerplate'
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
